# Site settings
title: Bradonomics
description: The Blog of Brad West
google-plus: #https://plus.google.com/103163741383795666289
twitter: #"@bradonomics"
baseurl: "/econ"
url: https://snowdj.github.io/econ

# Jekyll configuration
permalink: /:title/
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
encoding: utf-8
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  #  - jekyll-paginate
defaults:
- scope:
    path: ""
    type: posts
  values:
    layout: post
- scope:
    path: ""
    type: pages
  values:
    layout: page

include: ["_pages"]

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "gulpfile.js", "package.json", "_config-dev.yml", "_drafts"]
